### PR TITLE
Bump zend-stdlib minimum version

### PR DESCRIPTION
**Pull request by olegpro**
Provide a narrative description of what you are trying to accomplish:

- [ ] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [ ] Detail the original, incorrect behavior.
  - [ ] Detail the new, expected behavior.
  - [ ] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [ ] Are you creating a new feature?
  - [ ] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [ ] Is this related to quality assurance?
  

- [ ] Is this related to documentation?

### CODE REVIEW

**Comment by michalbundyra** [comment]
@olegpro What problem does it solve?

**Comment by olegpro** [comment]
> @olegpro What problem does it solve?

Allows the use of the zendframework/zend-servicemanager version 3.4

**Comment by michalbundyra** [comment]
@olegpro 

> Allows the use of the zendframework/zend-servicemanager version 3.4

How come it's not possible now?
Requirement is `^` so any version >= 3.1 and < 4.0.
https://jubianchi.github.io/semver-check/#/^3.1.0/3.2.1

The latest build from master: 
https://travis-ci.org/zendframework/zend-config-aggregator/jobs/550006812#L349

**Comment by olegpro** [comment]
@webimpress hmm .. i have so:

```

  Problem 1
    - Can only install one of: zendframework/zend-stdlib[3.2.1, 3.1.0].
    - Can only install one of: zendframework/zend-stdlib[3.2.1, 3.1.0].
    - Can only install one of: zendframework/zend-stdlib[3.2.1, 3.1.0].
    - zendframework/zend-servicemanager 3.4.0 requires zendframework/zend-stdlib ^3.2.1 -> satisfiable by zendframework/zend-stdlib[3.2.1].
    - Installation request for zendframework/zend-servicemanager ^3.4 -> satisfiable by zendframework/zend-servicemanager[3.4.0].
    - Installation request for zendframework/zend-stdlib (locked at 3.1.0) -> satisfiable by zendframework/zend-stdlib[3.1.0].

```

**Comment by michalbundyra** [comment]
@olegpro 

Can you explain, please, what you are trying to do?

I believe there is no problem with the package.
I guess that probably you need run `composer update` ...

**Comment by olegpro** [comment]
@webimpress 

Yes, did `composer update zendframework/zend-servicemanager` (changing in composer.json `^3.3` to `^3.4`).

Now tried to:
```
- composer remove zendframework/zend-servicemanager
- composer require zendframework/zend-servicemanager
```

and this solved the problem :)

**Comment by michalbundyra** [comment]
@olegpro 

Cool, you can also do this:
```bash
composer update zendframework/zend-servicemanager --with-dependencies
```

so it will update also dependencies of the provided package.

Glad the issue is resolved now.

**Pull request closed without merging**
