### PR TITLE
Added zendframework/zend-config-aggregator-modulemanager as suggestion

### PR DESCRIPTION
**Pull request by boesing**
To use modules which were originally created for `zend-mvc`, I would like to use a `ZendModuleProvider`, which parses the `zend-mvc` structure. 

Zend Modules provide configurations by the `getConfig` method.
They might provide dependencies with the `service_manager` key or by implementing the `ServiceProviderInterface` from `zendframework/zend-modulemanager`.

I created a class which just executes the methods and parse them into the new dependency structure.

### CODE REVIEW

**Comment by weierophinney** [comment]
This is definitely an awesome idea!

However, I hesitate to add it to this library, which is fairly agnostic about sources. I would suggest instead that this functionality be split into a separate package that users can opt-in to if they want to use zend-mvc modules. If you create the repo, we can fork it or have you assign ownership to the zendframework organization.

**Comment by boesing** [comment]
I've updated the PR and created a public repository [boesing/zend-config-aggregator-modulemanager](https://github.com/boesing/zend-config-aggregator-modulemanager) which could be forked/moved to the `zendframework` organization.
Feel free to fork or to provide me ownership to the organization.

The project should be integrated into the documentation process, since there are links within the Markdown files which are pointing to the official documentation repository.

**Comment by weierophinney** [comment]
Thanks, @boesing!

**Comment by boesing** [comment]
@weierophinney Please note that the suggested package is not yet available through packagist, since it should be moved/forked into the zendframework organization and then added to packagist.

Same is for #19

**Comment by weierophinney** [comment]
I'd added it before merging. ;-)

**Pull request merged**
